### ISSUE TITLE
Chase giving errors but not showing up

### ISSUE THREAD

**Issue by anfedorov** [wealthorg/wegrowwealth#10]
When I to to connect my Chase account, I first see:
![image](https://user-images.githubusercontent.com/9820/40272379-0df4873e-5b61-11e8-9775-c4194b8b8b1f.png)
And then:
![image](https://user-images.githubusercontent.com/9820/40272378-0c4850be-5b61-11e8-9b5b-5e9ad69ae811.png)

But it does not show up in balances.

**Comment by jdimatteo** [comment]
This seems to be a bug in error handling.

Your chase account already has 3 connections, 1 with status `challenges` and 2 with status `incorrect_credentials`.

```
{
      "username": "94faec0677584dc1a8af5ad5aff2903b",
      "status": "challenges",
      "user_id": 4275022,
      "created": "2018-05-18T17:47:52Z",
      "last_good_sync": null,
      "is_disabled": false,
      "institution_name": "Chase Bank",
      "value": null,
      "last_sync": "2018-05-18T19:28:28Z",
      "institution_id": 12,
      "auto_updates": true,
      "config_instructions": null,
      "id": 5694566
    },
    {
      "username": "94faec0677584dc1a8af5ad5aff2903b",
      "status": "incorrect_credentials",
      "user_id": 4275022,
      "created": "2018-05-18T17:48:39Z",
      "last_good_sync": null,
      "is_disabled": false,
      "institution_name": "Chase Bank",
      "value": null,
      "last_sync": "2018-05-18T19:28:28Z",
      "institution_id": 12,
      "auto_updates": true,
      "config_instructions": null,
      "id": 5694580
    },
    {
      "username": "94faec0677584dc1a8af5ad5aff2903b",
      "status": "incorrect_credentials",
      "user_id": 4275022,
      "created": "2018-05-18T17:58:13Z",
      "last_good_sync": null,
      "is_disabled": false,
      "institution_name": "Chase Bank",
      "value": null,
      "last_sync": "2018-05-18T19:28:29Z",
      "institution_id": 12,
      "auto_updates": true,
      "config_instructions": null,
      "id": 5694718
    },
```

**Comment by jdimatteo** [comment]
I worked around the bug by deleting the three above connections.

After deleting the 3 previous chase connections it no longer shows the "You already have a connection message".

I was able to proceed in setting up the account, MFA to your email address and got this far:

![image](https://user-images.githubusercontent.com/3752732/40279331-e39143f4-5bfd-11e8-8580-e49c838a7288.png)

**Comment by jdimatteo** [comment]
Steps to reproduce the bug:

1. go to https://wegrowwealth.org/connect
2. click "Connect Your Account"
3. select an account you don't already have a connection for
4. enter invalid username and password, e.g. ![image](https://user-images.githubusercontent.com/3752732/40279351-4f455996-5bfe-11e8-9ec7-153444ab8bcc.png)
5. click "Connect"
6. a message shows "Your username or password is incorrect. Please try again."
7. click the X, then "Done"
8. go to https://wegrowwealth.org/connect
9. repeat steps 1-3
expected behavior: behavior exactly like first time following steps 1-3
actual behavior: shows message "You already have a connection to Fidelity. Continue if you'd like to add a different connection."  
![image](https://user-images.githubusercontent.com/3752732/40279377-e67afed8-5bfe-11e8-9f90-dfacd0aa2413.png)

Maybe we need to cleanup incompletely setup connections before opening the ui connect widget

**Comment by jdimatteo** [comment]
Another variation of the bug:

1. go to https://wegrowwealth.org/connect
2. click "Connect Your Account"
3. select an account which you own with MFA but don't already have a WeGrowWealth.org connection for
4. enter valid username and password
5. click "Connect"
6. follow instructions for MFA but when prompted for the MFA answer enter something invalid
expected behavior: you are reprompted for an MFA answer
actual behavior: shows "Connection in Progress" for more than 60 seconds
![image](https://user-images.githubusercontent.com/3752732/40279412-71984b38-5bff-11e8-9ee6-ff091f1b0774.png)

After waiting 60 seconds with no visible progress, a user might refresh the page.  They will then get a confusing message:

![image](https://user-images.githubusercontent.com/3752732/40279442-cdce40e2-5bff-11e8-9c59-5bd2edc3dc62.png)

And proceeding with correct credentials will give an even more confusing message and prevent user from continuing:

![image](https://user-images.githubusercontent.com/3752732/40279460-17f2896c-5c00-11e8-8015-9958b9c1dea1.png)

**Comment by jdimatteo** [comment]
@anfedorov I deleted your incomplete Chase connection.  Please confirm you can add your account now.

Let's leave this issue open until I improve the error handling to not have the unexpected behavior described in this issue and the comments.

**Comment by jdimatteo** [comment]
If we do have to delete incomplete connections via the API before opening the UI widget, note that the delete call appears to be asynchronous so we might have to call the get connection api to verify it is completely deleted before opening the UI widget.  Hopefully the UI widget has some better support for modifying existing connections.

**Comment by anfedorov** [comment]
@jdimatteo did you mean to make all that public? would it make sense to have a policy about not making customer data public?

**Comment by anfedorov** [comment]
looks like Chase is working. could we expose all the connections I have in the UI so that I can remove them myself to debug this?
